[workspace]
# wgpu requires the newer resolver
resolver = "2"
members = ["ssbh_wgpu", "ssbh_wgpu_viewer", "ssbh_wgpu_test", "nutexb_wgpu", "nutexb_wgpu_viewer"]

[workspace.dependencies]
ssbh_data = "0.19.0"
wgpu = "25.0.2"
glam = "0.28.0"
