[package]
name = "ssbh_wgpu_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
wgpu = "0.20.1"
futures = "0.3"
log = "0.4.17"
simple_logger = "2.1.0"
glam = { version = "0.28.0", features = ["bytemuck"] }
ssbh_wgpu = { path = "../ssbh_wgpu" }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", rev = "acda3a2", features = ["strum"] }
pico-args = "0.5.0"