[package]
name = "ssbh_wgpu_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27"
wgpu = "0.14.0"
futures = "0.3"
log = "0.4.17"
simple_logger = "2.1.0"
glam = { version = "0.21.3", features = ["mint", "bytemuck"] }
ssbh_wgpu = { path = "../ssbh_wgpu" }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features = ["strum"] }