[package]
name = "ssbh_wgpu_test"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
wgpu = "0.12.0"
nutexb = "0.6.0"
ssbh_wgpu = { path = "../ssbh_wgpu" }
log = "0.4.17"
simple_logger = "2.1.0"
globwalk = "0.8.0"
