[package]
name = "ssbh_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26"
glam = { version = "0.20.2", features = ["mint", "bytemuck"] }
wgpu = "0.12.0"
futures = "0.3"
bytemuck = { version = "1.7", features = [ "derive" ] }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features = ["strum1"] }
globwalk = "0.8.0"
rayon = "1.5.1"
nutexb_wgpu = { path = "../nutexb_wgpu" }
serde_json = "1.0.81"
strum = { version = "0.23", features = ["derive"] }
wgpu_text = "0.6.1"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.3.5"

[build-dependencies]
wgsl_to_wgpu = { git = "https://github.com/ScanMountGoat/wgsl_to_wgpu" }

[[bench]]
name = "animate_skel"
harness = false