[package]
name = "ssbh_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.21.3", features = ["mint", "bytemuck"] }
wgpu = "0.14.0"
bytemuck = { version = "1.7", features = [ "derive" ] }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features = ["strum"] }
walkdir = "2"
rayon = "1.5.1"
nutexb_wgpu = { path = "../nutexb_wgpu" }
serde_json = "1.0"
strum = { version = "0.24.1", features = ["derive"] }
wgpu_text = "0.6.4"
log = "0.4.17"
glyph_brush = "0.7.4" # TODO: avoid this dependency?
arbitrary = { version = "1", optional = true, features = ["derive"] }
image = "0.24.2"
prc-rs = "1.5.2"
topological-sort = "0.2.2"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.3.5"

[build-dependencies]
wgsl_to_wgpu = { git = "https://github.com/ScanMountGoat/wgsl_to_wgpu" }

[features]
arbitrary = ["dep:arbitrary", "ssbh_data/arbitrary"]

[[bench]]
name = "animate_skel"
harness = false