use std::fmt::Write;

fn main() {
    // TODO: Only rerun if the shader change?
    let wgsl_source = std::fs::read_to_string("src/shader.wgsl").unwrap();

    // Generate the Rust bindings and write to a file.
    let mut text = String::new();
    writeln!(&mut text, "// File automatically generated by build.rs.").unwrap();
    writeln!(&mut text, "// Changes made to this file will not be saved.").unwrap();
    let options = wgsl_to_wgpu::WriteOptions {
        derive_bytemuck: true,
        ..Default::default()
    };
    text += &wgsl_to_wgpu::create_shader_module(&wgsl_source, "shader.wgsl", options).unwrap();

    std::fs::write("src/shader.rs", text.as_bytes()).unwrap();
}
