[package]
name = "nutexb_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.1"
nutexb = "0.7.0"
log = "0.4.17"
bytemuck = { version = "1.7", features = [ "derive" ] }
thiserror = "1.0"

[build-dependencies]
wgsl_to_wgpu = "0.12.0"
