// File automatically generated by build.rs.
// Changes made to this file will not be saved.
pub mod bloom {
    include!(concat!(env!("OUT_DIR"), "/bloom.rs"));
}
pub mod bloom_combine {
    include!(concat!(env!("OUT_DIR"), "/bloom_combine.rs"));
}
pub mod floor_grid {
    include!(concat!(env!("OUT_DIR"), "/floor_grid.rs"));
}
pub mod model {
    include!(concat!(env!("OUT_DIR"), "/model.rs"));
}
pub mod outline {
    include!(concat!(env!("OUT_DIR"), "/outline.rs"));
}
pub mod overlay {
    include!(concat!(env!("OUT_DIR"), "/overlay.rs"));
}
pub mod post_process {
    include!(concat!(env!("OUT_DIR"), "/post_process.rs"));
}
pub mod renormal {
    include!(concat!(env!("OUT_DIR"), "/renormal.rs"));
}
pub mod skeleton {
    include!(concat!(env!("OUT_DIR"), "/skeleton.rs"));
}
pub mod skinning {
    include!(concat!(env!("OUT_DIR"), "/skinning.rs"));
}
pub mod swing {
    include!(concat!(env!("OUT_DIR"), "/swing.rs"));
}
pub mod variance_shadow {
    include!(concat!(env!("OUT_DIR"), "/variance_shadow.rs"));
}
