// File automatically generated by build.rs.
// Changes made to this file will not be saved.
pub mod bloom;
pub mod bloom_combine;
pub mod model;
pub mod model_depth;
pub mod post_process;
pub mod renormal;
pub mod skinning;
