[package]
name = "nutexb_wgpu_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27"
futures = "0.3"
wgpu = "0.14.0"
nutexb = "0.6.0"
log = "0.4.17"
nutexb_wgpu = { path = "../nutexb_wgpu" }